// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rhodium.Data;

#nullable disable

namespace Rhodium.Migrations
{
    [DbContext(typeof(RhodiumContext))]
    partial class RhodiumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Rhodium.Data.RhodiumUserConfig", b =>
                {
                    b.Property<ulong>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferredMeasurementUnit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferredTemperatureUnit")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("UserConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
